/*
  Lesson 01 - Metadata,Read, add, and remove rows
  Student:João Victor Franco da Costa   
  Date:15/09/2026 noite 7:30 - 9:30
*/

USE ULHT_DB26;
GO



--A1
SELECT TOP (5)
EMPLOYEE_ID,
CONCAT(LAST_NAME, ', ', FIRST_NAME) AS formal_name
FROM HR.EMPLOYEES;

--A2
SELECT TOP (5)
EMPLOYEE_ID,
LOWER(CONCAT(EMAIL,'@example.org')) AS email_address
FROM HR.EMPLOYEES;


--A3
SELECT TOP(5)
LAST_NAME,
LEN(LAST_NAME) AS last_name_length
FROM HR.EMPLOYEES ORDER BY (LEN(LAST_NAME)) DESC;

--A4
SELECT TOP(5)
EMPLOYEE_ID,
SALARY,
(SALARY*3) AS quarter_salary,
(SALARY*14) AS annual_salary
FROM HR.EMPLOYEES;

--A5
SELECT TOP(5)
EMPLOYEE_ID,
HIRE_DATE,
DATEADD(MONTH,6,HIRE_DATE) AS review_date
FROM HR.EMPLOYEES;

--B1
SELECT TOP(5)
EMPLOYEE_ID,
ISNULL(COMMISSION_PCT, 0) AS COMMISSION_PCT
FROM HR.EMPLOYEES;

--B2
SELECT TOP(5)
EMPLOYEE_ID,
SALARY,
ISNULL(COMMISSION_PCT, 0) AS COMMISSION_PCT,
(SALARY*ISNULL(COMMISSION_PCT, 0)) AS comission_amount
FROM HR.EMPLOYEES;

--B3
SELECT TOP(5)
EMPLOYEE_ID,
SALARY *14 + (SALARY * 14 *(ISNULL(COMMISSION_PCT, 0))) AS annual_total
FROM HR.EMPLOYEES ORDER BY (SALARY *14 + SALARY * 14 *(ISNULL(COMMISSION_PCT, 0))) DESC;

--B4
SELECT TOP(5)
EMPLOYEE_ID,
COALESCE(CAST(MANAGER_ID AS VARCHAR(5)), 'no manager') AS manager_label
FROM HR.EMPLOYEES;

-- C1
--SELECT TOP(5)
--EMPLOYEE_ID,
