/*
  Lesson 01 - Metadata,Read, add, and remove rows
  Student:João Victor Franco da Costa   
  Date:15/09/2026 noite 7:30 - 9:30
*/

USE ULHT_DB26;
GO


SELECT DB_NAME() AS database_name; 


SELECT *
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR';
    

SELECT TOP 1 * FROM HR.EMPLOYEES
WHERE LAST_NAME = 'SMITH';


SELECT top(1)
    FIRST_NAME,
    LAST_NAME,
    EMPLOYEE_ID
FROM HR.EMPLOYEES
WHERE LAST_NAME = 'Costa'AND FIRST_NAME = 'Joao'; 


Select 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME,
    SALARY,
    DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE SALARY > 10000 AND DEPARTMENT_ID<>80;


SELECT *
FROM HR.JOBS;


SELECT
FIRST_NAME,
LAST_NAME
FROM HR.EMPLOYEES
WHERE JOB_ID = 'AD_PRES';


SELECT 
DEPARTMENT_ID,
DEPARTMENT_NAME,
MANAGER_ID,
LOCATION_ID
FROM HR.DEPARTMENTS WHERE DEPARTMENT_NAME = 'IT';


SELECT *
FROM HR.EMPLOYEES WHERE DEPARTMENT_ID = 60;


SELECT *
FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = 053;

SELECT 
COLUMN_NAME
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR' AND TABLE_NAME = 'EMPLOYEES' AND IS_NULLABLE = 'NO';


IF NOT EXISTS (SELECT 1 FROM HR.EMPLOYEES WHERE EMPLOYEE_ID = 053)
BEGIN
 INSERT INTO HR.EMPLOYEES (
    EMPLOYEE_ID, 
    FIRST_NAME, 
    LAST_NAME, 
    PHONE_NUMBER, 
    HIRE_DATE, 
    JOB_ID, 
    SALARY, 
    DEPARTMENT_ID
) VALUES (
  053,
  'João',
  'Costa',
  '931938655',
  GETDATE(),
  'IT_PROG',
  10000,
  60
);
END;

SELECT * 
FROM HR.EMPLOYEES 
WHERE EMPLOYEE_ID = 053;

DELETE FROM HR.EMPLOYEES 
WHERE EMPLOYEE_ID = 053;

SELECT * 
FROM HR.EMPLOYEES 
WHERE EMPLOYEE_ID = 053;